Feature/#13 seats screen UI
SOPT-all/35-COLLABORATION-ANDROID-CGV pull request #16
Opened 2024-11-22 17:52 UTC by tunaunnie

## *📌 Issue*
- closed #13 

## *💻 Work Description*
- SeatSelection 스크린(UI)과, 그 안에 들어가는 컴포넌트들을 구현했습니다.
  - SeatScreenTopBar 구현
  - TimeCompCardRow 구현
  - SeatSelectionChangeButton 구현
  - SeatSelectionChipRow 구현
  - SeatSelectionConfirmRow 구현
  - SeatConfirmationModal 구현
  
## *📸 Screenshot*

https://github.com/user-attachments/assets/6c453100-438f-415b-addb-c8a6d1d0a5f2
-> 원래 SeatScreen 처음에 진입하자마자 모달이 하나 뜨는 것까지 구현한 상태인데 (코드에 들어가 있음), 에뮬레이터에서 자꾸 작동이 안 돼서 첫 번째 모달 띄우는 부분만 주석처리하고 찍은 영상입니다..! 모달 컴포넌트만 따로 프리뷰로 보면 잘 동작하는데 혹시 클론받아서 두 개의 모달이 다 잘 뜨는지 확인해주시면.. 정말 감사하겠습니다 ㅜㅠ

https://github.com/user-attachments/assets/6127f952-0e9b-4b62-abb0-e5fc9b2a010b
<img width="260" alt="image" src="https://github.com/user-attachments/assets/1269b1a2-55c0-439f-abb1-625723c00eea">
<img width="154" alt="image" src="https://github.com/user-attachments/assets/1969580a-c9ad-438a-bc1e-d2be4e7edbce">
<img width="197" alt="image" src="https://github.com/user-attachments/assets/b8644a8d-e44d-4c97-83d8-d5f116605efc">
https://github.com/user-attachments/assets/38679544-c42a-41c0-a64e-a37e39fcb3ef

## *💭 To Reviewers*
-SeatSelectionModal1에서 총 선택한 인원 수가 0명 이상인 경우에 '좌석 선택' 버튼이 빨갛게 활성화되는 코드도 비즈니스 로직이라고 생각해서 우선은 내버려 뒀습니다! (TimeCompCard 활성화도 마찬가지) 차차 해당 부분을 고쳐봐도 괜찮을 것 같다면, 리뷰 남겨주시면 바로바로 반영하겠습니다! 지금 코드 상황에서 고쳐가야 할 부분을 순차적으로 알려주시면 조금씩 리팩토링해보겠습니닷

2024-11-23 15:05 UTC, 0se0 requested changes
솝커톤 하느라 바쁠텐데.. 이랬다 저랬다 하는 리드라 미안해...!😖

2024-11-23 15:05 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/core/designsystem/component/card/CompTimeCard.kt
> +            .size(width = 90.dp, height = 64.dp)
이렇게 컴포넌트 사이즈를 고정 dp로 주는 것이 아닌 컴포넌트 요소들의 패딩 값으로 조절해준 후 스크린에 넣었을 때, 전체 스크린에서의 디피로 조절해주면 더 좋을 거 같아요

2024-11-23 15:05 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/core/designsystem/component/card/CompTimeCard.kt
> +    endTime: LocalDateTime,
양지발이야... 내가 미안해...
오늘 서버 통신을 배우며 생각하였는데, 
이 부분 string으로 주는 것이 맞는 것 같애.. 너는 다 계획이 있었구나..
못난 리드라 미안해....

2024-11-23 15:05 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/core/designsystem/component/card/CompTimeCard.kt
> +    val formattedEndTime = endTime.format(timeFormatter)
이 부분이 시간 포멧팅 부분이여서 비즈니스 로직에 가깝다는 생각이 지금 들었사옵니다.. 서버 통신할 때 뷰모델 부분에서 시간 포멧팅을 해주면 될 것 같사옵니다.. 
미안하옵니다....🥹

2024-11-23 15:05 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/core/designsystem/component/chip/Chip.kt
> +        modifier = Modifier
```suggestion
    modifier: Modifier = Modifier,
    content: String
){

    Box(
        modifier = modifier
```

2024-11-23 15:05 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/seats/SeatSelectionChangeButton.kt
> +            .size(width = 66.dp, height = 24.dp)
여기도 이렇게 전체 사이즈를 확정지어 주는 것이 아닌, 패딩으로 조절하면 좋을 거 같아요!
혹여나 이렇게 하신 이유가 따로 있을까요?

2024-11-23 15:05 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/seats/SeatSelectionChangeButton.kt
> +            .clip(RoundedCornerShape(8.dp))
여기 순서도 클립으로 라운드를 먼저 깎은 후에 보더를 주는 것은 어떨까요? border를 먼저 하고 clip을 하면 테두리도 같이 잘릴 수 있는 상황도 발생할 수 있을 거 같아요!

2024-11-23 15:05 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/seats/SeatSelectionChipRow.kt
> +    contents: List<String>,
persistantlist 사용은 어떠실지요!

2024-11-23 15:05 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/seats/SeatSelectionChipRow.kt
> +}
오 이렇게 한번에 주는 방법을 생각하셨네요!
저였다면 일일히 만들었을 것만 같은,,,

2024-11-23 15:05 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/seats/SeatSelectionConfirmRow.kt
> +                color = Color.Black
여기 이렇게 컬러를 주면 저희 design system의 color가 반영되고 있는 것이 맞나요? 그냥 Black으로 주셔야 할 거 같은데 한번 확인 부탁드려요!!

2024-11-23 15:05 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/seats/SeatSelectionModal1.kt
> +    chipContents: List<String>,
여기도 persistant 사용 한번 고려해보시면 어떠실지요??
아니면 list를 사용하신 따른 이유가 있을까요?

2024-11-23 15:05 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/seats/SeatSelectionModal1.kt
> +        containerColor = Color.White
여기 색상도 한번 확인 부탁드립니당

2024-11-23 15:05 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/seats/SeatSelectionConfirmRow.kt
> +                color = Color.Black
여기 컬러두요!

2024-11-23 15:05 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/seats/SeatSelectionStepperRow.kt
> +            color = Color.Black
여기 컬러 한번 봐주세용

2024-11-23 15:05 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/seats/Stepper.kt
> +                    painter = painterResource(id = R.drawable.ic_seats_minus),
아이콘 페인터 리소스 말고 벡터로 사용해주세요!
혹시 ic_seats_minus가 png라면 painterResource로 해주셔요!

2024-11-23 15:05 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/seats/Stepper.kt
> +                    .background(Color.White, RoundedCornerShape(8.dp)),
여기도 색상 한번만 확인하기!!

2024-11-23 15:05 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/seats/Stepper.kt
> +                    painter = painterResource(id = R.drawable.ic_seats_plus),
여기도 painterResource 확인해주셔요!

2024-11-23 15:20 UTC, 0se0 reviewed
추가적으로 seats 부분에서만 사용하는 component는 component 패키지를 따로 만들어서 그 안에 파일들을 넣어주세요!!

2024-11-25 08:56 UTC, tunaunnie commented on app/src/main/java/org/sopt/cgv/core/designsystem/component/card/CompTimeCard.kt
> +    endTime: LocalDateTime,
ㅋㅋㅋㅋ 뒷걸음정답 ...🫢 괜차나 이러면서 더 배우게 되는 것 같당!!

2024-11-25 09:23 UTC, kamja0510 approved these changes
짱짱맨 리뷰 답장 잘 확인할게~

2024-11-25 09:23 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/core/designsystem/component/card/CompTimeCard.kt
> +                modifier = modifier
modifier를 계속 물려받으면 계산할 때 조금 힘들지 않나요?

2024-11-25 09:23 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/core/designsystem/component/card/CompTimeCard.kt
> +            verticalArrangement = Arrangement.SpaceBetween
이 부분이 필요할까요?

2024-11-25 09:23 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/core/designsystem/component/card/CompTimeCard.kt
> +                    if(isMorning){
너무 좋네요

2024-11-25 09:23 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/core/designsystem/component/chip/Chip.kt
이 파일은 제가 더 고쳐놓겠쑵니다 닫기 아이콘 있는 버전으로

2024-11-25 09:23 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/seats/SeatConfirmationModal.kt
> +fun SeatConfirmationModal(
preview를 보니 modal의 상단에 당길 수 있는 표시?가 남아있는 거 같은데 제거해 보심이 어떠신가요!

2024-11-25 09:23 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/seats/SeatConfirmationModal.kt
> +                Spacer(modifier = Modifier.width(16.dp))
이런것 보면은 디자인의 사이 간격은 12px이라고 나와있는데 16dp를 주는 이유가 궁금합니다! 진짜 질문

2024-11-25 09:23 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/seats/SeatConfirmationModal.kt
> +                style = Typography.head6_b_17,
어떨때는 CGVTheme.typography.head6_b_17 로 적용하시다가 어쩔때는 이렇게 적용하시는데 하나로 통일 하시는게 좋을 것 같아요! 저는 CGVTheme의 typography를 쓴다고 명시하면 좋을 것 같긴합니다

2024-11-25 09:23 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/seats/SeatSelectionChipRow.kt
> +        horizontalArrangement = Arrangement.spacedBy(8.dp, Alignment.CenterHorizontally),
오우 이건 어떤 문법이죵?

2024-11-25 09:23 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/seats/SeatSelectionConfirmRow.kt
> +            modifier = Modifier,
이런줄은 필요 없을 것 같아요!

2024-11-25 09:23 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/seats/SeatConfirmationModal.kt
> +                    text = "뒤로가기",
confirm창에는 뒤로가기가 없는데 혹시 디자인이 변경되었난요?

2024-11-25 10:13 UTC, tunaunnie commented on app/src/main/java/org/sopt/cgv/feature/seats/SeatSelectionChangeButton.kt
> +            .size(width = 66.dp, height = 24.dp)
하드코딩한 다른 이유가 있는 건 아니고, 패딩값을 인자로 주어서 동적으로 크기가 조절되도록 하는 방식을 더 일반적으로 사용한다는 사실을 잘 몰랐어요..! 세영쓰가 버튼 구현한 거 보고 완벽하게 이해해갑니당.. 🤩

2024-11-25 10:29 UTC, tunaunnie commented on app/src/main/java/org/sopt/cgv/feature/seats/SeatSelectionChipRow.kt
> +}
다른 뷰에서 chip이 늘 3개가 아니라 여러 개가 오는 row가 사용될 수도 있을 것 같아서 이렇게 반복문으로 구현했습니다...!

2024-11-25 10:31 UTC, tunaunnie commented on app/src/main/java/org/sopt/cgv/feature/seats/SeatSelectionConfirmRow.kt
> +                color = Color.Black
다들 엄청나게 예리하군요..........................이걸어케찾았지

2024-11-25 10:34 UTC, tunaunnie commented on app/src/main/java/org/sopt/cgv/feature/seats/SeatSelectionModal1.kt
> +    chipContents: List<String>,
여기서도 list를 사용한 다른 이유가 있는 건 아니고, 저번에 persistentList를 써보려고 시도하다가 라이브러리 설치에서 뭔가 잘 안돼서 포기하고 임시방편으로 List로 넣어둿읍니다.. 세영이 거 받고 나니까 문제없이 잘되는군뇨.. 나도 .toml 에러에 쫄지안는사람이되고십다..

2024-11-25 10:34 UTC, tunaunnie commented on app/src/main/java/org/sopt/cgv/feature/seats/SeatSelectionModal1.kt
> +    chipContents: List<String>,
덕분에 List와 PersistentList의 차이 제대로 알구갑니다! compose에서는 웬만하면 (실시간으로 자주 바뀌는 정보를 담지만 않으면) PersistentList를 사용하는 것으로 이해해두 괜찮을까용?

2024-11-25 10:40 UTC, tunaunnie commented on app/src/main/java/org/sopt/cgv/feature/seats/Stepper.kt
> +                    painter = painterResource(id = R.drawable.ic_seats_minus),
덕분에 컴포즈에서 벡터 아이콘을 사용할 때는 painterResoucre보다 vectorResource 사용하는 것이 더 최적하된 방법이라는 사실 알아갑니당 . .

2024-11-25 10:41 UTC, tunaunnie commented on app/src/main/java/org/sopt/cgv/feature/seats/Stepper.kt
> +                    painter = painterResource(id = R.drawable.ic_seats_minus),
사실 이름부터 painterResource인데 내가 넘 의심없이 사용한 것 같당. . 바보

2024-11-25 10:47 UTC, tunaunnie commented on app/src/main/java/org/sopt/cgv/core/designsystem/component/card/CompTimeCard.kt
> +                modifier = modifier
세영이가     modifier: Modifier = Modifier, 이거 모든 컴포넌트에 추가해주라고 해서 다 인자로 넘겨받은 modifier를 물려받아 사용하는 것으로 해뒀는데, 상위에서 modifier를 인자로 넘겨받기만 하구 사용하지 않는건가용??

2024-11-25 10:49 UTC, tunaunnie commented on app/src/main/java/org/sopt/cgv/core/designsystem/component/card/CompTimeCard.kt
> +            verticalArrangement = Arrangement.SpaceBetween
진짜 빼두 괜찮네요..🫢 아직도 정렬에 익숙하지 않아서 spacer나 align을 덕지덕지 붙이지 않고도 예쁘고 깔끔하게 배치하는 법을 잘 모르겠어요ㅜㅠ ..

2024-11-25 10:50 UTC, tunaunnie commented on app/src/main/java/org/sopt/cgv/core/designsystem/component/chip/Chip.kt
세영님 코드리뷰도 반영해뒀습니당 (cgvButton처럼 인자로 패딩값 받아서 동적으로 칩 크기 변경되도록)

2024-11-25 10:56 UTC, tunaunnie commented on app/src/main/java/org/sopt/cgv/feature/seats/SeatConfirmationModal.kt
> +fun SeatConfirmationModal(
modalBottomSheet의 인자에 dragHandle = { } 을 추가하니까 엄청 간단하게 없어지네요!

2024-11-25 10:56 UTC, tunaunnie commented on app/src/main/java/org/sopt/cgv/feature/seats/SeatConfirmationModal.kt
> +fun SeatConfirmationModal(
눈썰미가 다들 대단하네요 ... 재민님은 진짜 클라의 자질이 있으신거같아요 ..

2024-11-25 10:59 UTC, tunaunnie commented on app/src/main/java/org/sopt/cgv/feature/seats/SeatConfirmationModal.kt
> +                Spacer(modifier = Modifier.width(16.dp))
px와 dp의 차이를 고려해서 변환한 거였다면 정말 멋진대답이었겠지만.. 실수로 잘못넣은거라 잽싸게 수정했습니당ㅜ

2024-11-25 11:06 UTC, tunaunnie commented on app/src/main/java/org/sopt/cgv/feature/seats/SeatSelectionChipRow.kt
> +        horizontalArrangement = Arrangement.spacedBy(8.dp, Alignment.CenterHorizontally),
spacedBy도 쓰고싶고 중앙정렬도 하고싶은데 horizontalArrangment를 두번 쓰면 오류가 나길래 찾아보니까 이렇게 한번에도 쓸 수 있더라고요! 더 간단한 방법으로 가독성 좋게 고칠 방법이 있을까요??

2024-11-25 11:07 UTC, tunaunnie commented on app/src/main/java/org/sopt/cgv/feature/seats/SeatConfirmationModal.kt
> +                    text = "뒤로가기",
바로 고쳤습니다ㅜㅜ 꼼꼼히 봐주셔서 너무너무 감사합니다.!!!!

2024-11-25 12:14 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/seats/component/SeatConfirmationModal.kt
> +        containerColor = Color.White
발견!
이래서 저는 놓진 부분이 있을 수 있으니 ctrl+R을 눌러서 검색을 한다음에 Replace를 해요
무슨 말인지 모르겠으면 연락하세용

2024-11-25 12:15 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/seats/component/SeatConfirmationModal.kt
> +        containerColor = Color.White
전체 프로젝트에서 검색할땐 ctrl + shift + R

2024-11-25 12:23 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/core/designsystem/component/card/CompTimeCard.kt
> +                modifier = modifier
일단 저도 다 추가는 해놓구 부모계층(?)의 영향을 받는 아이들이 있을때만 modifier를 쓰긴해요
예를 들면 부모가 할당받은 width의 1/4을 받고 싶으면 부모 컴포넌트로 부터 Modifier.weight(0.25f) 를 물려받아서 쓰는 방식으로??
세영이 방법이 더 맞을 수도! 전 뭔가 신경쓸게 많아져서 안쓰게 되더라구요

2024-11-25 12:24 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/seats/SeatConfirmationModal.kt
> +fun SeatConfirmationModal(
캬 혼자 알아내시다니
감사합니다 ㅎ

2024-11-25 12:24 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/seats/SeatConfirmationModal.kt
> +                Spacer(modifier = Modifier.width(16.dp))
ㅋㅋㅋㅋㅋㅋㅋㅋ 나이스

2024-11-25 12:28 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/seats/SeatSelectionChipRow.kt
> +        horizontalArrangement = Arrangement.spacedBy(8.dp, Alignment.CenterHorizontally),
바로 생각나는 거는 없네요? 좋은 것 배운거같아요

2024-11-25 14:32 UTC, tunaunnie commented on app/src/main/java/org/sopt/cgv/feature/seats/component/SeatConfirmationModal.kt
> +        containerColor = Color.White
수정 완료!!

2024-11-25 15:26 UTC, 0se0 requested changes
우왕 너무 수고 많으셨습니다~! 훨씬 보기 좋아졌네요!
제가 남긴 리뷰들 한번 확인해주시고 수정해주시면 좋을 거 같아요!

2024-11-25 15:26 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/core/designsystem/component/card/CompTimeCard.kt
> +    val leftSeatsColor = if (isActivated) PrimaryRed400 else Green
요 부분 
```suggestion
    .background(if (isActivated) White else Gray700)
    
    .background(if (isActivated) Gray200 else Gray700),
   
```
이렇게 주는 거 어떠실지요!

2024-11-25 15:26 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/core/designsystem/component/card/CompTimeCard.kt
> +                        .background(if (isActivated) Gray200 else Gray700),
여기처럼요!

2024-11-25 15:26 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/seats/SeatSelectScreen.kt
> +
여기는 뷰모델에서 관리하는 것은 어떤가요?
꼭 여기에서 구현해야 하는 다른 이유가 있을까요?

2024-11-25 15:26 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/seats/component/SeatSelectionConfirmRow.kt
> +        modifier = Modifier.fillMaxWidth(),
여기에도 modifier인자가 있음 더 좋을 거 같아요!

2024-11-25 15:26 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/seats/component/SeatSelectionStepperRow.kt
> +fun StepperRow(label: String) {
여기도 modifier인자가 있음 더 좋을 거 같숨당

2024-11-25 15:26 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/seats/component/SeatSelectionTimeCardRow.kt
> +    var clickedCardIndex = remember { mutableStateOf(Int) }
요런 상태는 뷰모델에서 관리하는 편이 더 좋지 않을까요???

2024-11-25 15:26 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/seats/component/SeatsScreenTopBar.kt
> +        //TopBar 부분
모든 파일에서 이런 주석 부분을 지워주시면 좋을 거 같아요!

2024-11-25 15:26 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/seats/component/Stepper.kt
> +    var currentValue by remember { mutableStateOf(initialValue) }
이 부분도 상태관리를 뷰모델에서 하면 더 좋을 거 같아요!

2024-11-26 05:30 UTC, tunaunnie commented on app/src/main/java/org/sopt/cgv/core/designsystem/component/card/CompTimeCard.kt
> +    val leftSeatsColor = if (isActivated) PrimaryRed400 else Green
이렇게 하니까 쓸데없는 변수 선언도 줄일 수 있고, 가독성도 더 좋아지네요!

2024-11-26 08:55 UTC, tunaunnie commented on app/src/main/java/org/sopt/cgv/feature/seats/SeatSelectScreen.kt
> +
이번에 남겨주신 리뷰 덕분에, 어떠한 변수들을 뷰모델로 넘겨 관리해야 하는지 조금 더 명확히 이해한 것 같습니다..! 

(그런데 여전히 하위 컴포넌트에서 필요한 뷰모델을 상위 컴포넌트들에서 무한(..) 인자로 받아줘야 하는 건지?? <- 이 부분은 아직 정확하게 이해하지 못한 것 같아용..)

 그래도 하나하나 스스로 부딪히면서 알아가고 이해해가는 맛이 있는 것 같습니다 ....! 어떻게 보면 세영이 입장에서는 너무 당연한 것들을 하나하나 지적하느라 답답하고 고생스러울 수도 있을 것 같은데, 더 정진해서 빠르게 배워가겟습니당... 꼼꼼하고 정성스러운 리뷰 너무너무 고마워용

2024-11-26 08:55 UTC, tunaunnie commented on app/src/main/java/org/sopt/cgv/feature/seats/component/SeatSelectionStepperRow.kt
> +fun StepperRow(label: String) {
이것두 재민오빠가 남겨준 리뷰 기반으로 상위 컴포넌트에서 물려준 (인자로 받은) modifier를 도대체 어디까지 적용해줘야 하는 건지 약간 더 공부해볼 수 있어서 좋았서용

2024-11-26 09:59 UTC, 0se0 requested changes
수고많으셨습니다~! 
컴포넌트에 뷰모델을 인자로 주신 부분만 추가적으로 더 공부해보시고 반영하면 훨씬 좋을 거 같아요!!

2024-11-26 09:59 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/seats/component/SeatSelectViewModel.kt
뷰모델 파일은 컴포넌트에 있으면 안됩니당
컴포넌트 패키지는 ui를 재사용할 수 있는 파일들로 이뤄주세요!

2024-11-26 09:59 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/seats/component/SeatSelectionModal1.kt
> +    viewModel: SeatSelectViewModel,
뷰모델 의존성을 제거해주세요!

```suggestion
    stepperValues: Map<String, Int>,
    onStepperIncrease: (String) -> Unit,
    onStepperDecrease: (String) -> Unit,
```
ViewModel을 직접 주입하는 대신 필요한 데이터와 이벤트 핸들러만 전달받도록 변경해주세요!
이렇게 바꾼다면 컴포저블의 재사용성을 높일 수 있을 거 같습니당

2024-11-26 09:59 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/seats/component/SeatSelectionStepperRow.kt
> +    viewModel: SeatSelectViewModel,
```suggestion
     value: Int,
    onIncrease: () -> Unit,
    onDecrease: () -> Unit
```
이 코드에서도 ViewModel 직접 참조 대신 필요한 상태와 이벤트만 매개변수로 받도록 변경해주세요! 이렇게 바꾸면 컴포넌트가 특정 ViewModel에 종속되지 않아 다양한 상황에서 재사용이 가능할 거 같아요!

2024-11-26 09:59 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/seats/component/SeatSelectionStepperRow.kt
> +    viewModel: SeatSelectViewModel,
또한 이 컴포넌트 함수명을 파일명과 일치시키면 조금 더 보기 쉬울 거 같아요!

2024-11-26 09:59 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/seats/component/SeatSelectionTimeCardRow.kt
> +    viewModel: SeatSelectViewModel,
```suggestion
    selectedIndex: Int,           
    onCardClick: (Int) -> Unit,   
```
여기서도 ViewModel 직접 참조 대신 선택된 인덱스(selectedIndex)와 클릭 이벤트 콜백(onCardClick)을 매개변수로 받도록 변경하여 상태 관리의 책임을 상위 컴포넌트로 이동시키게 된다면 컴포넌트의 재사용성 향상시킬 수 있을 거 같아요! 또한 컴포넌트가 특정 ViewModel에 종속되지 않아 더 다양하게 사용 가능할 거 같습니당

2024-11-26 09:59 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/seats/component/SeatsScreenTopBar.kt
> +    viewModel: SeatSelectViewModel,
```suggestion
    selectedTimeCardIndex: Int,         
    onTimeCardClick: (Int) -> Unit,     
    onBackClick: () -> Unit             
```
여기서도 ViewModel 의존성을 제거하고 필요한 상태와 이벤트 콜백만 매개변수로 받도록 변경하면 좋을 거 같아요! 이유는 위와 같습니당

2024-11-26 09:59 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/seats/component/Stepper.kt
> +    viewModel: SeatSelectViewModel
```suggestion
    value: Int,                
    onIncrease: () -> Unit,    
    onDecrease: () -> Unit     
```
여기서도 지금까지와 같은 이유로 이렇게 바꾸면 좋을 거 같아요! 
추가적으로 label이 ViewModel의 stepperValues Map에서 해당 Stepper의 값을 찾는 키로 사용되고 있는 거 같은데 맞을까요? 위와 같이 바꾸면 value를 직접 받아오므로 Map에서 값을 찾을 필요가 없어져서 아래 코드가 필요 없어지게 될 거 같은데 한번 확인해주시면 감사하겠습니다!

2024-11-26 09:59 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/seats/SeatSelectScreen.kt
> +            )
제가 단 코드리뷰를 반영하면 이제 여기 부분과

2024-11-26 09:59 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/seats/SeatSelectScreen.kt
> +            )
여기 부분까지 수정되어야 합니당

2024-11-26 09:59 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/seats/SeatSelectScreen.kt
> +
여기에 
`onNavigateBack: () -> Unit = {}` 이렇게 네비게이션 콜백을 추가하면
SeatsScreenTopBar에서 뒤로가기를 할 때 
```
SeatsScreenTopBar(
    onBackClick = onNavigateBack 
)
```

이렇게 사용하여 네비게이션 로직을 상위 컴포넌트로 이동시킨다면 화면 간 이동을 더 유연하게 처리할 수 있을 거 같아요!

2024-11-27 11:11 UTC, 0se0 approved these changes
수고하셨습니다~!!ㅎㅎ 체고!!

2024-11-27 17:42 UTC, merged