[Feature/#10] TimeScreen UI
SOPT-all/35-COLLABORATION-ANDROID-CGV pull request #19
Opened 2024-11-26 16:32 UTC by kamja0510

## *📌 Issue*
- closed #10 

## *💻 Work Description*
- 컴포넌트 만들기

## *📸 Screenshot*
- <video src = "https://github.com/user-attachments/assets/e634abf6-0b68-4168-9f4b-e0658f50ca1e">

## *💭 To Reviewers*
- 뷰를 완성시켜보았습니다!

2024-11-27 13:43 UTC, 0se0 requested changes
수고 많으셨습니다~!!!
조금만 더 파이팅!!!!!

2024-11-27 13:43 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/core/designsystem/component/button/CGVButton.kt
> +    borderColor: Color = Color.Transparent,
엇 요거는 develop에 있는 코드가 아닌가요? 고친게 아니라면
머지할떄 develop에 있는 것으로다가 반영해주세요~!

2024-11-27 13:43 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/core/designsystem/component/card/CompTimeCard.kt
> +    Box(
요부분 지원이 컴포넌트 같은데..!
나중에 지원이 바뀐 코드로 반영 해주세요!

2024-11-27 13:43 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/core/designsystem/theme/Color.kt
> +val Gradient_modal = Brush.verticalGradient(
미친 눈썰매

2024-11-27 13:43 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/core/designsystem/component/chip/Chip.kt
> +import androidx.compose.runtime.mutableStateOf
여기 임포트 삭제해주세요!

2024-11-27 13:43 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/core/designsystem/component/chip/Chip.kt
> +) {
```suggestion
fun Chip(
    content: String,
    modifier: Modifier = Modifier,
    inTime: Boolean = false,
    onTheaterSelected: ((String) -> Unit)? = null
) {
```
저도 이 부분을 많이 놓치는데,
Modifier 매개변수는 반드시 첫 번째 선택적 매개변수여야 합니다!!
(주의 경고를 한번 봐주시면 좋을 거 같아요)

2024-11-27 13:43 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/core/designsystem/component/chip/Chip.kt
> +                        if (onTheaterSelected != null) onTheaterSelected(content)
```suggestion
                     .clickable { onTheaterSelected?.invoke(content) }
```
요렇게는 어떠신지요?
Kotlin의 null 안전 연산자(?.)를 활용하여 코드를 좀 더 간결히 만들고 가독성을 향상시킬 수 있을 거 같아요!

2024-11-27 13:43 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/component/CGVTabRow.kt
여기 파일에는 프리뷰가 만들어지지 않는 것인가요?
그게 아니라면 프리뷰를 만들어주세요!

2024-11-27 13:43 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/component/TimeScreen.kt
>  ) {
여기 timescreen 부분을 component에서 빼서 time패키지 안에서의 파일로 관리해주시면 좋을 거 같아요.
또한 TimeRoute, TimeScreen을 분리하여

`TimeRoute: 상태 관리와 이벤트 처리`
`TimeScreen: UI 렌더링`

이렇게 나누면 UI 로직과 비즈니스 로직 분리 상태 관리 용이할 거 같습니다!

2024-11-27 13:43 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/component/TimeScreenAuditoriumAndTimeSelection.kt
> +)
여기는 나중에 서버 통신을 하면서 별도의 파일로 만들어 패키징 하실 예정이신거죠??

2024-11-27 13:43 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/component/TimeScreenDateSelectionTab.kt
> +    dateList: List<Date>,
persistantlist 어떠세욥!!!

2024-11-27 13:43 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/component/TimeScreenDateSelectionTab.kt
> +                )
여기서 .clip()으로 먼저 모서리를 자르고 background를 적용하면 좋을 거 같아요!
이렇게 하면 clickable 영역도 모서리가 깎인 형태로 제한되어서요!!

2024-11-27 13:43 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/component/TimeScreenMovieSelectionSection.kt
> +                    .background(color = Black, shape = RoundedCornerShape(5.dp))
여기서도 .clip을 주는 거 어떠실지요!

2024-11-27 13:43 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/component/TimeScreenMovieSelectionSection.kt
> +        }
cgv버튼 컴포넌트에서 조금만 수정하면 활용가능할 거 같은데..!
이렇게 따로 박스로 만들어주신 이유가 있을까요?

2024-11-27 13:43 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/component/TimeScreenTimeSelectionHeader.kt
> +import org.sopt.cgv.core.designsystem.theme.Black
여기 사용하지 않는 임포트 지워주세요!

2024-11-27 13:43 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/component/TimeScreenTimeSelectionHeader.kt
> +            }
여기도 background 를 주기 전 .clip으로 먼저 깎으면 좋을 거 같아요!
그리고 여기 버튼도 이렇게 box로 넣어주신 것은 따로 빼서 컴포넌트화 할 필요가 없다고 판단하셔서 이렇게 주신건가요??

2024-11-27 13:43 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/component/TimeScreenTobBar.kt
> +                modifier = Modifier.width(204.dp),
가로 길이를 이렇게 지정해주신 이유가 있을까요??
추가적으로 CGVTabRow에도 프리뷰를 추가해주시면 확인하기 더 좋을 거 같습니다!

2024-11-27 13:43 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/component/TimeScreenTobBar.kt
> +                        unselectedContentColor = White
이렇게 주신 이유가 있을까요?

2024-11-27 13:48 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/core/designsystem/component/card/CompTimeCard.kt
> +    Box(
넵 일단 배껴와서 구현했습니다!

2024-11-27 13:49 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/core/designsystem/component/button/CGVButton.kt
> +    borderColor: Color = Color.Transparent,
넵 이름을 잘못 배껴왔네요..

2024-11-27 13:50 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/core/designsystem/component/chip/Chip.kt
> +                        if (onTheaterSelected != null) onTheaterSelected(content)
이런식으로 할 수 있군요!

2024-11-27 13:50 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/time/component/CGVTabRow.kt
만들어 보겠습니다!

2024-11-27 13:51 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/time/component/TimeScreenAuditoriumAndTimeSelection.kt
> +)
네 아직 패키징을 어떻게 할 지 잘 몰라서 나두었습니다

2024-11-27 13:53 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/time/component/TimeScreenDateSelectionTab.kt
> +                )
제가 그거를 고려해서 clickable을 앞에 두기도 했고, background를 지정하면 영역에는 아무지장없이 뒷배경만 저모양으로 색칠되는 것 아닌가요?

2024-11-27 13:55 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/time/component/TimeScreenDateSelectionTab.kt
> +                )
아 모서리부분의 색칠 안된 곳을 클릭했을때 클릭되는 것이 어색한 동작일 수 있다는 말씀이신거죠?

2024-11-27 13:56 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/time/component/TimeScreenMovieSelectionSection.kt
> +        }
엇 상상도 못했습니다

2024-11-27 13:58 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/time/component/TimeScreenTobBar.kt
> +                        unselectedContentColor = White
디자인 상 선택된부분도 하얀색이고 선택이 되지 않는 부분도 하얀색이기 때문입니다
색 변화는 없고 인디케이터의 이동만 있습니다!

2024-11-27 14:03 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/component/TimeScreenTobBar.kt
> +                        unselectedContentColor = White
혹시 저 코드가 인디케이터 이동 색상의 관련된 코드일지요..!!??
그게 아니라면 굳이 저렇게 색상을 주지 않아도 될 거 같아서요!
선택된부분도 하얀색이고 선택이 되지 않는 부분도 하얀색이니까요!

2024-11-27 14:09 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/component/TimeScreenDateSelectionTab.kt
> +                )
맞습니당!!!

2024-11-27 14:10 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/component/TimeScreenMovieSelectionSection.kt
> +        }
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2024-11-27 14:24 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/time/component/TimeScreenTobBar.kt
> +                        unselectedContentColor = White
아하 이해했습니다! unselected의 기본값이 selected를 따라가기 때문이네요

2024-11-27 15:57 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/time/component/TimeScreenDateSelectionTab.kt
> +    dateList: List<Date>,
전달하는 리스트는 persistentList인데 List로 받는다고 되어있어도 오류가 안나네요..

2024-11-27 16:01 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/time/component/TimeScreenTobBar.kt
> +                modifier = Modifier.width(204.dp),
wrapContentSize로 할 수 있도록 CGVTabRow를 변경했습니다!

2024-11-27 17:41 UTC, tunaunnie approved these changes
열심히 고민하면서 구현하신 게 보이는 것 같습니당... 보면서 늘 많이 배워갑니다!! 고생하셨어유

2024-11-27 17:41 UTC, tunaunnie commented on app/src/main/java/org/sopt/cgv/feature/time/component/TimeScreen.kt
>  ) {
저두 TimeScreen은 컴포넌트 패키지의 밖으로 빼서 관리하는 게 좋을 것 같습니당

2024-11-27 17:41 UTC, tunaunnie commented on app/src/main/java/org/sopt/cgv/feature/time/component/TimeScreen.kt
>      modifier: Modifier = Modifier
이거 근데 왜 한 번도 안 쓰셨나요??
저는 (세영이가 하라고해서) 매 컴포넌트의 첫번째 인자로 다 modifier를 받아주긴 하는데,
어디에서 물려받은 이 모디파이어를 쓰고, 어디에서는 그 컴포넌트에서 독립적으로 관리해 주어야 하는지 늘 조금씩 애매하더라고요. 유연한 컴포넌트의 크기 처리(?)를 위함이라면, 컴포넌트를 둘러싸고있는 가장 외곽 도형(?)의 크기가 동적으로 변해야 한다고 생각해서 전 늘 컴포넌트를 가장 바깥에서 싸고 있는 Column이나 Row에 이 전달받은 modifier를 먹이는데, 재민님은 이렇게 물려받은 modifier를 어떻게 사용하시는지 궁금합니당 ...

2024-11-27 17:41 UTC, tunaunnie commented on app/src/main/java/org/sopt/cgv/feature/time/component/CGVTabRow.kt
> +    Surface(
surface를 사용하신 이유가 있나요??

2024-11-27 17:41 UTC, tunaunnie commented on app/src/main/java/org/sopt/cgv/feature/time/component/TimeScreen.kt
> +                stickyHeader {
결국 해내셧군요..👍👍

2024-11-27 17:41 UTC, tunaunnie commented on app/src/main/java/org/sopt/cgv/feature/time/component/TimeScreen.kt
> +            if (selectedTheaters.value.contains(it)) selectedTheaters.value -= it
우와 이거 보고 많이 배워갑니당

2024-11-27 18:06 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/component/TimeScreenDateSelectionTab.kt
> +    dateList: List<Date>,
ㅎㅎ.. PersistentList는 List의 구현체이기 때문입니당
> (PersistentList = List 인터페이스를 구현한 불변 리스트)

2024-11-28 06:43 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/time/component/CGVTabRow.kt
> +    Surface(
음 이거는 기존에 존재하는 TabRow라는 컴포저블 함수에서 변형한 것이라 Surface가 사용되어있길래 사용하였습니다!
생각해보니 Surface가 머가 다른지는 잘 모르는것 같네요

2024-11-28 06:45 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/time/component/TimeScreen.kt
>      modifier: Modifier = Modifier
저도 두분의 코드를 보면서 무조건 처음 한번은 modifier를 사용하는 것이 맞다고 생각합니다.
나중에 변형할때도 편할 것이고 아무것도 전달되지 않았을때는 어짜피 기본값으로 Modifier를 사용하기 때문입니다. 다음 pr때 다 바꿔놓겠습니다!

2024-11-28 08:36 UTC, 0se0 approved these changes
수고많으셨어요!

2024-11-28 08:36 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/component/CGVTabRow.kt
> +    Surface(
Surface는 Material Design의 개념을 따르는 컴포넌트입니당

2024-11-28 08:36 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/component/CGVTabRow.kt
> +    spacing: Dp = 8.dp, // 탭 간 간격
주석 지워주셔요!

2024-11-28 08:36 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/component/CGVTabRow.kt
> +    indicatorColor: Color = Color.White,
아 이거 지금 봤는데 저의 디자인시스템 컬러가 아닌 이 컬러를 사용해주신 이유가 따로 있나요?

2024-11-28 08:36 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/component/CGVTabRow.kt
> +    Surface(
근데 혹시 여기 tabrow는 제가 홈뷰 컴포넌트에서 만든 TabBar로 할 수 없나요???
뭔가 다른게 있을까요..!!?

2024-11-28 08:36 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/component/TimeScreenMovieSelectionSection.kt
> +        modifier = Modifier
```suggestion
    Box(
        modifier = modifier
```

2024-11-28 08:36 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/component/TimeScreenTimeSelectionHeader.kt
> +        modifier = Modifier
```suggestion
    modifier: Modifier = Modifier
) {
    Box(
        modifier = modifier
```

2024-11-28 08:36 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/component/TimeScreenTobBar.kt
> +        modifier = Modifier
```suggestion
        modifier = modifier
```

2024-11-28 08:38 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/time/component/CGVTabRow.kt
> +    indicatorColor: Color = Color.White,
실수입니다 눈썰미 최고

2024-11-28 08:42 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/time/component/TimeScreenMovieSelectionSection.kt
> +        modifier = Modifier
18번 pr에 다 반영했습니다 ㅎ

2024-11-28 08:46 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/time/component/CGVTabRow.kt
> +    Surface(
애니메이션이 있어요 ㅎ

2024-11-28 09:33 UTC, merged