[UI/#1] color setting
SOPT-all/35-COLLABORATION-ANDROID-CGV pull request #2
Opened 2024-11-18 15:56 UTC by tunaunnie

## *📌 Issue*
- closed #1

## *💻 Work Description*
- 메인 컬러 지정 완료했습니다!

## *📸 Screenshot*
-

## *💭 To Reviewers*
-

2024-11-19 01:32 UTC, 0se0 requested changes
assigness와 리뷰어에 재민오빠도 설정해주면 완벽합니당!!!

2024-11-19 01:32 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/ui/theme/Color.kt
너무 수고하셨습니다!ㅎㅎ 한가지 수정할 점은 
core-designsystem-theme 아래에 컬러 표를 따로 만들어서 위치 변경을 해주시면 더 좋을 거 같아요!!

2024-11-19 12:50 UTC, 0se0 requested changes
assignee에는 본인 넣어주세용!

기존 디벨롭 브랜치에서 ui-theme패키지 안에 있던 것을 core-designsystem-theme 아래로 바꾸되, 피그마 색상만 추가해주시면 된다고 생각하면 쉬울 거 같아요!
지금 무언가가 많이 섞여있는 거 같은데 다시 한번 더 확인해주시면 좋을 거 같아요!

2024-11-19 12:50 UTC, 0se0 commented on app/build.gradle.kts
> +
요기 한 줄 추가 된 거 제거 해주세요!

2024-11-19 12:50 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/core/designsystem/component/card/SeatSelectScreenTimeCard.kt
> +            verticalArrangement = Arrangement.SpaceBetween
요기 컴포넌트 구현 부분도 피알에 같이 올려주신게 맞을까요..??

2024-11-19 12:50 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/core/designsystem/theme/Color.kt
> +package org.sopt.cgv.ui.theme
패키지가 잘 못 되었어요!

2024-11-19 12:50 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/core/designsystem/theme/Theme.kt
> +    tertiary = Yellow
여기 색상이 바뀐 이유가 있을까요??

2024-11-19 13:02 UTC, tunaunnie commented on app/src/main/java/org/sopt/cgv/core/designsystem/component/card/SeatSelectScreenTimeCard.kt
> +            verticalArrangement = Arrangement.SpaceBetween
제가 지금 컴포넌트 구현 작업도 동시에 하고 있어서 git add . 하는 과정에서 같이 올라간 것 같은데, git add할 때 이번 이슈에 해당하는 작업물만 넣어서 커밋 올리면 되는 걸까요?? 바뀐 폴더가 너무 많아서 별 생각 없이 git add .를 했는데, 생각해보니 코드리뷰 할 때 이것저것 섞여서 알아보기 힘들 것 같네요...!! (ㅜㅜ 너무 서투른 점이 많아서 죄송합니당...🥹🥹)

2024-11-19 13:02 UTC, kamja0510 requested changes
Color.kt만 건드리신 곳으로 돌아가야 할 것 같아요!

2024-11-19 13:06 UTC, tunaunnie commented on app/src/main/java/org/sopt/cgv/core/designsystem/theme/Theme.kt
> +    tertiary = Yellow
피그마에 Color Scheme와 관련한 내용이 없어서, 우선 기존에 들어있던 코드들에 오류가 나지 않도록 랜덤한 값들을 넣어둔 상황입니다..! (제거하겠습니다ㅠㅠ) 그런데 혹시 피그마의 primary_red랑 gray_scale이 이 ColorTheme에 해당하는 걸까요?? primary_red랑 gray_scale의 컬러들을 하나하나 개별적인 이름으로 등록해뒀는데, 보통 이런 scale값들은 보통 Scheme으로 넣어서 관리하는지 궁금합니다... !

2024-11-19 13:22 UTC, tunaunnie commented on app/src/main/java/org/sopt/cgv/core/designsystem/theme/Theme.kt
> +    tertiary = Yellow
피그마의 요구사항에는 다크모드/일반모드 구분이 없어서, 이 부분 코드를 아예 삭제해도 괜찮을까요?

2024-11-19 13:45 UTC, kamja0510 approved these changes
저기 아이콘들은 남아있어도 되는 걸까요?

2024-11-19 13:45 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/core/designsystem/theme/Theme.kt
> +    tertiary = Purple
요기는 뭐 보고 바꾸신건가요?

2024-11-19 14:01 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/core/designsystem/theme/Theme.kt
> +    tertiary = Yellow
혹시 이 부분 코드가 저희 앱 돌아가는 것에 있어 영향을 미친다고 생각하신걸까요??
저는 상관이 없을 거 같아 유지해도 괜찮을 것 같다고 판단했었거든요!

2024-11-19 15:56 UTC, 0se0 requested changes
다시 확인 부탁드려용

2024-11-19 15:56 UTC, 0se0 commented on app/src/main/res/drawable/ic_seats_plus.xml
> +</vector>
요기 벡터 이미지들도 다 지워주셔요! 컬러 세팅에서는 필요하지 않은 부분인 거 같아요!!

2024-11-19 15:56 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/core/designsystem/theme/Color.kt
> +val BackgroundOpacity1 = Color(0x99000000)
여기에 원래 있었던 기존 theme-color에 있는 색상들을 추가해주세요~

2024-11-20 03:01 UTC, 0se0 approved these changes
추가적으로 feature패키지의 mainactivity에서 CGVTheme이 제대로 임포트 되어있는지도 확인해주세요! 2가지만 더 확인하고 머지해주시면 감사하겠습니다~

2024-11-20 03:01 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/core/designsystem/theme/Theme.kt
>  import android.app.Activity
여기는 사용하지 않는 임포트인거 같은데, 확인해주시고 맞다면 지워주세요!

2024-11-20 13:47 UTC, merged