[Refactor/#18] Time MVVM 적용
SOPT-all/35-COLLABORATION-ANDROID-CGV pull request #20
Opened 2024-11-27 17:36 UTC by kamja0510

## *📌 Issue*
- closed #18 

## *💻 Work Description*
- TimeScreen에 MVVM적용
- TimeRoute 구현

## *📸 Screenshot*
- 달라진 기능 없음

## *💭 To Reviewers*
- 이렇게 하는 것이 맞는건인가요!

2024-11-28 03:04 UTC, 0se0 requested changes
지금도 코드도 너무 좋습니다!!

현재 MVVM코드에서
각각의 상태 변경을 위한 개별 함수들이 존재합니다.
직접적인 상태 수정을 하고
Side Effect 처리가 없습니다.!

이를 보완하여 MVI 구조로 가기 위해서는 
모든 사용자 액션이 Event로 정의되면 좋을 거 같아요!
단방향 데이터 흐름 (Event -> Intent -> State)
또한 Side Effect가 명시적으로 분리되면 더 좋을 거 같습니다!

```
M(model)
앱의 상태를 나타내는 불변 데이터

V(view)
UI를 렌더링하고 사용자 입력을 Intent로 변환

I(intent)
사용자의 의도/행동을 나타내는 이벤트
```

2024-11-28 03:04 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/core/designsystem/component/button/CgvButton.kt
> +    modifier: Modifier = Modifier,
WOW.

2024-11-28 03:04 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/core/designsystem/component/card/CompTimeCard.kt
> +    onClick: () -> Unit
여기 아직 지원이 코드 반영 안된거죠?? +주석은 지워주세요!

2024-11-28 03:04 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/core/designsystem/component/chip/Chip.kt
> +            ),
👍👍

2024-11-28 03:04 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/core/designsystem/theme/Color.kt
>  )
혹시 이 브랜치 디벨롭에서 머지한 후에 새로 파신 브랜치가 아닌가요?

2024-11-28 03:04 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/TimeRoute.kt
이 파일 안에 route와 screen을 넣으면 보기 더 쉬울 거 같아요!
(물론 갠취가 있겠지만..! 저는 HomeRoute파일 안에 HomeRoute() HomeScreen()이 있습니당

2024-11-28 03:04 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/TimeRoute.kt
> +    val timeScreenUiState by timeScreenViewModel.uiState.collectAsStateWithLifecycle()
collectAsState을 사용하시지 않고, collectAsStateWithLifecycle()을 사용하신 이유가 있을까요?

2024-11-28 03:04 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/TimeRoute.kt
> +}
!! :: 사용 잘 하셨네요!!!
그럼 :: 을 사용하는 이유도 아시나요??

2024-11-28 03:04 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/TimeRoute.kt
> +    val timeScreenViewModel = viewModel<TimeScreenViewModel>()
```suggestion
fun TimeRoute(
    navigateToSeat: () -> Unit,
     timeScreenViewModel: TimeScreenViewModel
) {
```
Route는 네비게이션과 상태 관리를 담당하고, 
Screen: UI 표시와 사용자 인터랙션만 담당한다고 이해하시면 쉬울 거 같아요! 

기존 코드에서는TimRoute가 ViewModel도 생성하고 UI, 네비게이션, 상태관리까지 다 책임지었지만, 위와 같이 바꾸게 된다면 ViewModel 생성 책임을 분리하고 Route는 네비게이션과 상태관리에만 집중하여 외부에서 주입받은 ViewModel을 사용하게 하면 더 좋을 거 같아요!

2024-11-28 03:04 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/TimeScreenViewModel.kt
> +class TimeScreenViewModel() : ViewModel() {
```suggestion
class TimeScreenViewModel : ViewModel() {
```

2024-11-28 03:04 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/TimeScreenUiState.kt
> +    val isSheetOpen: Boolean = true
1. 네이밍을 TimeScreenState으로 하는 것은 어떠신가요??
음..! 저의 경우에는 UiState는 데이터의 로딩 상태를 관리하기 위한 sealed class로 만들어서 각 라우트의 스테이트 안에서 관리해주고 있습니다!
> ex)
> data class StoreDetailState(
>     val storeDetail: UiState<StoreDetailResponseEntity> = UiState.Loading,
>     val isLiked: Boolean = false,
> ...)
그래서 
`데이터를 가져오는 중일 때: UiState.Loading`
`데이터 가져오기 성공했을 때: UiState.Success(data)`
`오류가 발생했을 때: UiState.Error(message)`
이 3가지를 나누어서 각각의 Screen으로 넘어가고 있어요!

그래서 파일명과 클래스 이름을 TimeScreenUiState보다 TimeScreenState으로 하는 것이 좀 더 어울리지 않을까라고 생각됩니다! 

2. 변수명을 조금 더 간결하게 가져가는 건 어떠실지요?!!
tabIndex, region, theaters, topBarTabIndex, poster, date, day이렇게요!
이렇게 하면 보기에도 더 쉽고 상태 참조 시에 더 직관적으로 사용할 수 있을 거 같아요!

2024-11-28 03:04 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/TimeScreenViewModel.kt
> +
현재 대부분의 상태 업데이트 함수들에서 값 비교 체크를 하고 계신데, 꼭 했어야만 하는 이유가 있을까요?

2024-11-28 06:57 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/time/TimeRoute.kt
아하 그렇게 하겠습니당

2024-11-28 06:58 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/time/TimeRoute.kt
> +    val timeScreenViewModel = viewModel<TimeScreenViewModel>()
이해하였숩니다!

2024-11-28 07:01 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/time/TimeRoute.kt
> +    val timeScreenUiState by timeScreenViewModel.uiState.collectAsStateWithLifecycle()
collectAsState가 StateFlow를 구독하는 함수인데 라이프 사이클을 고려하지 않고 compose가 띄워져있지 않을때도 계속 구독한다고 합니다. 이때 collectAsStateWithLifecycle()이 이것을 보안하기위해 나온 함수로 UI가 화면에 띄워져있을때만 데이터를 구독해 메모리 낭비를 방지합니다! 
제 과제 코드리뷰에도 한번 달렸어서 이것만 사용합니다

2024-11-28 07:03 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/time/TimeRoute.kt
> +}
일단 제가 처음 사용했을 때 알게된 지식은 함수를 호출하지 않고 그 자체를 전달하는 함수참조 연산자라고 알고 사용하고있습니다!

2024-11-28 07:05 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/time/TimeScreenViewModel.kt
> +
copy를 사용하기 때문에 같지 않을때도 리컴포지션이 일어나기 때문입니다!

2024-11-28 07:09 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/time/TimeScreenUiState.kt
> +    val isSheetOpen: Boolean = true
하나의 뷰이지만 TimeScreen에서 쓰이는 state인지 modal에서 쓰이는 state인지 제가 구현하면서도 헷갈리더라고요! 사실 자동완성 기능이 너무 좋아서 제가 변수명이나 함수명이 얼마나 긴지는 상관안쓰고 그 이름만 봐도 어떤 역할인지 알 수 있도록 네이밍을 하는데 어떻게 보시나요!

2024-11-28 07:10 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/core/designsystem/theme/Color.kt
>  )
다시 머지 하겠습니다!

2024-11-28 07:42 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/time/TimeScreenUiState.kt
> +    val isSheetOpen: Boolean = true
그리고 UiState에 대한 네이밍은 처음에 viewmodel을 공식문서로 봤을때 저렇게 하길래 따라했습니다!

2024-11-28 08:54 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/TimeScreenUiState.kt
> +    val isSheetOpen: Boolean = true
> 하나의 뷰이지만 TimeScreen에서 쓰이는 state인지 modal에서 쓰이는 state인지 제가 구현하면서도 헷갈리더라고요!

아 이것 때문이였군요! 그렇다면 state를 분리해주시면 어떨까요?? 기능적으로는 Screen과 Modal에 각각 다른 책임이 있으니까요!
```
ex)
TimeRouteState
ModalState
```

2024-11-28 09:10 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/time/TimeScreenUiState.kt
> +    val isSheetOpen: Boolean = true
대박 이런방법이 분리하고 네이밍 바꾸겠습니다~

2024-11-28 09:13 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/TimeScreenViewModel.kt
> +
음..! 현재 StateFlow를 사용하고 계신데, StateFlow의 특성에 대해 알고계시면 좋을 거 같아요!!

StateFlow는 기본적으로 distinctUntilChanged 동작을 포함하고 있어서, 값이 실제로 변경되었을 때만 새로운 값을 방출해줍니다!
StateFlow를 한번 타고 들어가보시면 사진 처럼 나와있는 걸 볼 수 있으실 거에요😊

distinctUntilChanged() 함수의 구현을 보시면, 
| StateFlow에서 타고 들어갔을 때 | distinctUntilChanged()타고 들어갔을 때 |
|---------|---------|
| ![Image 2](https://github.com/user-attachments/assets/b024576a-2d6e-407c-bf02-b2777e90002e) | ![Image 3](https://github.com/user-attachments/assets/b4b03680-5ac8-4055-91b4-1382073ab085) |

> Note that any instance of StateFlow already behaves as if distinctUntilChanged operator is applied to it,
so applying distinctUntilChanged to a StateFlow has no effect

모든 StateFlow 인스턴스는 이미 distinctUntilChanged 연산자가 적용된 것처럼 동작해서
따라서 StateFlow에 distinctUntilChanged를 적용해도 아무런 효과가 없다고 나와있어요!
(Operator fusion 부분에서 확인하실 수 있습니당)

따라서 현재 구현하신 값 비교 체크가 없어도 불필요한 리컴포지션은 일어나지 않을 것 같습니당

2024-11-28 09:25 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/time/TimeScreenViewModel.kt
> +
이거 진짜 혼자 알아내는데는 엄청 걸렸을 것 같은데 감사합니다..
참조가 변하면 참조하는 주소값이 달라지니까 값이 변한줄 알겠지! 라고 혼자 생각했네요

2024-11-29 06:41 UTC, tunaunnie commented on app/src/main/java/org/sopt/cgv/feature/time/TimeRoute.kt
> +fun TimeRoute(
Route라는 함수가 네비게이션 이동 & UI 그려주는 역할을 담당하고 있다는 기능이 잘 보이는 것 같아요! 👍

2024-11-29 06:49 UTC, tunaunnie approved these changes
Route랑 State 분리하신 거 보고 많이 배워갑니다!!

2024-11-29 06:49 UTC, tunaunnie commented on app/src/main/java/org/sopt/cgv/feature/time/TimeRoute.kt
> +fun TimeRoute(
Route라는 함수가 네비게이션 이동 & UI 그려주는 역할을 담당하고 있다는 기능이 잘 보이는 것 같아요! 👍

2024-11-29 06:49 UTC, tunaunnie commented on app/src/main/java/org/sopt/cgv/feature/time/TimeRoute.kt
> +    val timeModalState by timeScreenViewModel.timeModalState.collectAsStateWithLifecycle()
Screen의 상태, Modal의 상태를 분리해서 명명하니 훨씬 가독성 좋네요! 덕분에 collectAsStateWithLifecycle이라는 유용한 함수도 알아갑니다~~

2024-11-29 06:49 UTC, tunaunnie commented on app/src/main/java/org/sopt/cgv/feature/time/TimeRoute.kt
> +    )
어떤 인자들은 State에 담았던 것들을 불러오고, 어떤 인자들은 State에 담지 않고 그냥 뷰모델에 넣었다가 불러오는데 혹시 무슨 기준으로 구분하셨나용??
(State에 담고 -> 그 State를 Viewmodel에 담은 인자들 vs 그냥 Viewmodel에 바로 넣어두고 불러온 인자들)

2024-11-29 07:58 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/time/TimeRoute.kt
> +    )
저는 다 state에 담은 것 같습니다!
혹시 navigateToSeat를 말씀하시는 건가요?

2024-11-29 08:24 UTC, 0se0 approved these changes
고생하셨습니다!!

2024-11-29 08:33 UTC, merged