[UI/#7] time&seats screen 공통 컴포넌트 제작
SOPT-all/35-COLLABORATION-ANDROID-CGV pull request #8
Opened 2024-11-19 16:39 UTC by tunaunnie

## *📌 Issue*
- 이슈 7이긴 한데 아직 전부는 안함

## *💻 Work Description*
- CompTimeCard 제작 (time, seats 스크린에서 사용)
  - 아직 typography 적용 전
  - 아랫부분 text에서 미묘하게 정렬이 안맞음
- Stepper 제작 (seats 스크린에서 사용)
  - 아직 typography 적용 전
- SeatChoiceModalChip 제작  (time, seats 스크린에서 사용)
- ModalButton 제작 (time, seats 스크린에서 사용)
  - 아직 typography 적용 전
  - onclick 적용 전
  - isActivated 값에 따라서 비활성화/활성화하는 로직 적용 전

## *📸 Screenshot*
<img width="200" alt="image" src="https://github.com/user-attachments/assets/8be627ff-9e0d-42d8-9e78-d2492366df31">
<img width="226" alt="image" src="https://github.com/user-attachments/assets/c3e4a3b6-8fa8-4b40-bc51-8dac72d23124">
<img width="214" alt="image" src="https://github.com/user-attachments/assets/f654ba1c-e8e6-4fd5-9d69-7ceb2bcb5bb6">
<img width="131" alt="image" src="https://github.com/user-attachments/assets/df8c41bb-5f06-433e-b46c-e428456472c6">
<img width="263" alt="image" src="https://github.com/user-attachments/assets/e9f0043c-20ed-4ec5-8567-2313bd5a1a22">

## *💭 To Reviewers*
- 생각보다 요구사항을 정확히 맞추기가 어렵더라고요.. 수정사항 보내주시면 바로바로 반영하겠습니다!!

2024-11-20 03:23 UTC, 0se0 requested changes
1. 전체적인 컴포넌트 파일에서 사용하지 않는 import들을 지워주세요.
2. 서버에서 보내주는 값을 확인하고 인자로 넣어주세요!
ex)starttime, endtime
3. clickable이 설정된 것도 있고, 아닌 것도 있는데 norippleclick 확장함수를 만들어서 넣어주세요.
4. 컴포넌트 사용이 제대로 되고 있는 것이 맞는지 임시 화면을 만들어서 보여주세요!
5. 주석은 삭제해주세요! 모든 컴포넌트 인자에서 modifier을 전달해주는 것이 확장성에 더 좋을 거 같아요!
먼저 이 5가지를 수정해주신 후 리퀘스트 백 부탁드려용

2024-11-20 09:01 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/core/designsystem/component/button/ModalButton.kt
와 컴포넌트화 이렇게까지 할 수 있네요?
저는 다 다른 버튼이라 다 만들 것 같았는데

2024-11-20 13:50 UTC, tunaunnie commented on app/src/main/java/org/sopt/cgv/core/designsystem/component/button/ModalButton.kt
오히려 비효율적이구 헷갈리려나... 싶어서 다시 나눌까 고민중이어요 ㅎㅎㅜㅠ..

2024-11-22 11:54 UTC, 0se0 reviewed
리뷰 확인해주시고, 반영하신 후 screen 구현하시면서 컴포넌트도 같이 수정해보시면 더 좋을 거 같습니당, 컴포넌트에서 모든 기능을 만드는 것이 아닌 ui 보여지는 요소를 구현한다고 생각하면 좋을 거 같아욥!

2024-11-22 11:54 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/core/common/ModifierExtensions.kt
> +}
여기 norippleclick 제가 develop에 넣어 놓았으니 그거 사용해주시면 될 거 같아요!

2024-11-22 11:54 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/core/designsystem/component/card/CompTimeCard.kt
> +
onclick을 인자로 넣어주시고, 그 안에서 배경색을 조절하면 좋을 거 같아요!

2024-11-22 11:54 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/core/designsystem/component/button/ModalButton.kt
> +    }
버튼 크기를 고정 dp로 주는 것이 아닌, 텍스트를 기준으로 horizontalPadding, verticalPadding을 주신후 나중에 스크린에서 전체 화면에서의 패딩을 조절하면 기기 대응에도 더 좋을 거 같습니당

2024-11-22 11:54 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/core/designsystem/component/button/ModalButton.kt
> +    ) {
요거 디벨롭 확장함수 사용해주세요!

2024-11-22 11:54 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/seats/SeatSelectionModal1.kt
> +) {
modifier 인자를 추가해주세요!

2024-11-22 11:54 UTC, 0se0 approved these changes

2024-11-23 04:01 UTC, closed without merging