[Feature/#6] TimeScreen 극장 선택 모달 UI 구현
SOPT-all/35-COLLABORATION-ANDROID-CGV pull request #9
Opened 2024-11-21 08:42 UTC by kamja0510

## *📌 Issue*
- closed #6 

## *💻 Work Description*
- TimeScreen에 진입 시 띄워질 극장 선택 모달의 UI 구현

## *📸 Screenshot*
- <video src=https://github.com/user-attachments/assets/dce8e354-d716-43d9-b88e-88b89813f164>

## *💭 To Reviewers*
현재 아무 아키텍쳐도 적용되지 않았고, footer도 버튼과 chip의 공통 컴포넌트를 받게되었을때 제대로 구현하려고 합니다.

2024-11-21 15:11 UTC, 0se0 requested changes
수고많으셨습니다~! 
컴포넌트 패키지를 새로 만들어서 그 안에 파일을 넣어주시면 더 좋을 거 같아요.
그리고 각 컴포넌트에서 프리뷰 화면을 만들어주세요!!
또한 각 프리뷰 화면은 피그마와 일치하게 만들어주시면 더 좋을 거 같습니당!☺️

2024-11-21 15:11 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/ClickableVerticalRegionListInModal.kt
> +    modifier: Modifier = Modifier
여기에
selectedItem: String?,
onItemSelected: (String) -> Unit,
을 인자로 더 넣어주어 State Hoisting을 해주면 재사용성이 더 좋아질 수 있을 거 같아요!

2024-11-21 15:11 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/ClickableVerticalRegionListInModal.kt
> +        modifier = modifier,
contentPadding = PaddingValues(vertical = 12.dp)
이런식으로 padding을  LazyColumn 레벨에서 처리하면 재계산 최소화할 수 있을 거 같아욥
추가적으로 피그마에는 어떻게 나와있는지 제가 제대로 확인하지 못했지만 각 리스트 사이에 넣어야 할 간격이 있다면 verticalArrangement의 spacedBy를 활용해도 좋을 거 같아요!

2024-11-21 15:11 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/ClickableVerticalRegionListInModal.kt
> +                    .clickable { selectedItem = item }
norippleclickable 사용해주셔용 (제가 생각하기에 디자인에서 이 동작까지 구현해달라고 한 것이 아니기에 현재로선 norippleclickable을 사용하는 것이  맞다고 판단하였습니당)

2024-11-21 15:11 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/SelectableTheatersInModal.kt
> +    var isSelected by remember { mutableStateOf(false) }
이 부분을 State Hoisting 해서 선택 상태를 컴포넌트 외부로 이동시켜준다면 상태 관리에 더 좋을 거 같아요~

2024-11-21 15:11 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/SelectableTheatersInModal.kt
> +)
persistantlist와 list의 차이점을 공부해보시고 적용 판단 해보시면 좋을 거 같아요!

2024-11-21 15:11 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/SelectableTheatersInModal.kt
> +                    painter = painterResource(R.drawable.ic_time_modal_check),
[ImageBitmap과 ImageVector 비교](https://developer.android.com/develop/ui/compose/graphics/images/compare?hl=ko)
여기 참고해보시고 수정해주시면 좋을 거 같아요!!

2024-11-21 15:11 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/TheaterClassificationTabInModal.kt
> +) {
여기도 onTabSelected: (Int) -> Unit, 이렇게 State Hoisting을 해볼 수 있을 거 같아용 상태 관리 책임을 상위로 이동하는 것을 익혀보시면 좋을 거 같숨당
추가적으로 modifier 기본값을 인자로 넣어주세요!!

2024-11-21 15:11 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/TheaterClassificationTabInModal.kt
> +                    unselectedContentColor = Gray850
여기 부분도 `color = if (selectedTabIndex == index) PrimaryRed400 else Gray850` 이런식으로 사용할 수 있게 고쳐주시면 더 좋을 거 같아요!

2024-11-21 15:11 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/TheaterSelectionModalBottomSheet.kt
> +import androidx.compose.ui.graphics.Color
사용하지 않는 import는 지워주세요!!

2024-11-21 15:11 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/TheaterSelectionModalBottomSheet.kt
> +            val selectedIndex = remember { mutableStateOf(0) }
기존 파일에서 주의 경고가 나고 있다면 최대한 해결해주시면 좋을 거 같아요~!

2024-11-21 15:11 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/TheaterSelectionModalBottomSheet.kt
> +) {
Modifier 기본값 추가해주세요!

2024-11-21 15:11 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/TheaterSelectionModalBottomSheet.kt
> +    if (isSheetOpen) {
지금 상의 코드에서
```
var selectedTabIndex by remember { mutableStateOf(0) }
var selectedRegion by remember { mutableStateOf<String?>("추천 CGV") }
var selectedTheaters by remember { mutableStateOf(setOf<String>()) }
```
이렇게 상위에서 통합적으로 상태관리를 해볼 수 있을 거 같아요..!!

2024-11-21 15:11 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/TheaterSelectionModalFooter.kt
> +fun Chip(text: String, onClick: () -> Unit) {
요기 각자의 스타일이긴 하지만..ㅎ
```
fun Chip(
    text: String,
    onClick: () -> Unit
)
```
이렇게 해주시면 더 좋을 거 같숨다.
Modifier인자도 넣어주시면 더 좋을 거 같아요!

그리고 여기 칩은 버튼의 활성, 비활성 상태가 필요하지 않은 것인가요?

2024-11-21 15:11 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/TheaterSelectionModalFooter.kt
> +            .dropShadow(
여기 shadow를 사용할 수 없는 것 인가요??

2024-11-21 15:11 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/TheaterSelectionModalFooter.kt
> +                }
이렇게 컴포저블 내부에서 rememberCoroutineScope()를 사용하면  리컴포지션될 때마다 새로운 코루틴 스코프가 생성되어 진행 중인 코루틴이 취소되고 새로 시작되거나 불필요한 메모리를 사용하게 될 거 같아요!
상위에서 주입을 받아서 코루틴 생명주기를 상위에서 관리하고 스코프 재사용으로 리소스 절약하면 좋을 거 같다고 생각합니다!!

2024-11-21 15:24 UTC, tunaunnie commented on app/src/main/java/org/sopt/cgv/feature/time/TheaterSelectionModalBottomSheet.kt
> +                    theaterNames = listOf("구리", "압구정"),
이 부분 인자들 순서를 바꿔주는 게 추후 가독성에 더 좋을 것 같아요!

2024-11-21 15:24 UTC, tunaunnie commented on app/src/main/java/org/sopt/cgv/feature/time/TheaterSelectionModalBottomSheet.kt
> +                    theaterNames = listOf("구리", "압구정"),
detailRegionName 다음에 theaterNames가 오는 것이 조금 더 자연스러울 것 같습니당

2024-11-21 15:25 UTC, tunaunnie commented on app/src/main/java/org/sopt/cgv/feature/time/ClickableVerticalRegionListInModal.kt
> +                    .clickable { selectedItem = item }
궁금한 점!! 제가 norippleclickable 확장함수로 만들었는데 이런 확장함수도 다같이 컴포넌트처럼 돌려쓸 수 있나요??

2024-11-21 15:29 UTC, tunaunnie commented on app/src/main/java/org/sopt/cgv/feature/time/TheaterSelectionModalFooter.kt
> +}
각 컴포넌트 파일 아래에 preview 달아주시면 조금 더 리뷰 달기 수월할 것 같습니당..!

2024-11-21 16:11 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/time/TheaterSelectionModalFooter.kt
> +fun Chip(text: String, onClick: () -> Unit) {
요기 Footer 부분은 공통 컴포넌트가 merge되면 적용할 예정입니다!

2024-11-21 16:13 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/time/TheaterSelectionModalFooter.kt
> +            .dropShadow(
figma에서 주신 dropshadow가 그냥 shadow로는 구현하기 힘들어서 dropShadow 확장함수를 만들어보았습니다

2024-11-21 16:14 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/time/TheaterSelectionModalFooter.kt
> +                }
와 rememberCoroutineScope()에 대해서 좀 알아봐야겠습니다!

2024-11-21 16:14 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/time/TheaterSelectionModalBottomSheet.kt
> +                    theaterNames = listOf("구리", "압구정"),
오 맞는 말씀인거 같습니다.

2024-11-21 16:18 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/time/ClickableVerticalRegionListInModal.kt
> +        modifier = modifier,
헐 contentPadding이 있군요 그러고 start에 29.dp 패딩도 lazycolumn의 modifier에 넣어도 되겠네요!
LazyColumn에서 Box사이의 간격은 없습니다

2024-11-21 16:19 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/time/ClickableVerticalRegionListInModal.kt
> +    modifier: Modifier = Modifier
지금 호이스팅을 안해놓은 것이 많은데 mvi, mvvm중에 어떤 것을 쓸지 몰라서 놔두고 있습니다!
mvvm을 사용하면 viewmodel에 넣어두면 되는 것 맞죠?

2024-11-22 16:01 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/time/SelectableTheatersInModal.kt
> +)
persistentlist가 완벽 불변성을 보장해요!

2024-11-22 16:31 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/time/ClickableVerticalRegionListInModal.kt
> +                    .clickable { selectedItem = item }
돌려쓸 수 있지 않을까요! 사용완료

2024-11-22 16:49 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/time/TheaterSelectionModalBottomSheet.kt
> +import androidx.compose.ui.graphics.Color
이런거 어떻게 찾으시는거에요??
코드 다 클론하시나요?

아 저 저장하면 자동으로 ctrl + alt + o 하도록 해놨는데 가끔 먹통이 되네요..

2024-11-25 06:51 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/time/TheaterSelectionModalFooter.kt
> +                }
이것이 remember를 사용하기 때문에 재구성 시 새로운 코루틴 스코프가 생성되지 않는다고 합니다! 따라서 이 컴포저블의 생명주기 안에서만 행해지는 coroutine이라면 상위에서 따로 관리할 필요가 없다고 합니다! 만약 이 컴포저블 생명주기를 넘어 화면 전환시에도 행해저야 하는 작업들이라면 상위에서 관리가 필요하다고 합니다!

2024-11-25 07:08 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/time/TheaterClassificationTabInModal.kt
> +                    unselectedContentColor = Gray850
Tab이라는 기본 컴포저블에 color라는 변수가 없어서 이렇게 하였습니다! 가독성에 문제가 있을까요?
전 오히려 이렇게 parameter가 주어지니 더 편했습니다!

2024-11-25 15:43 UTC, 0se0 requested changes
반영 속도가 엄청 빠르시네요..! 수고 너무 많으셨습니다~ 
제가 남긴 리뷰 한번 확인해보시고 반영해주시면 좋을 거 같아요!!

2024-11-25 15:43 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/component/SelectableTheatersInModal.kt
> +    selectedTheaters: MutableState<Set<String>>,
selectedTheaters의 MutableState를 ViewModel로 이동하는 편이 더 좋지 않을까요? 상태 관리 부분인 거 같아서요! 아니면 이렇게 컴포넌트 인자로 주신 다른 이유가 있나요??

2024-11-25 15:43 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/component/SelectableTheatersInModal.kt
> +    selectedTheaters: MutableState<Set<String>>,
여기 부분도 위와 동일합니다!

2024-11-25 15:43 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/component/SelectableTheatersInModal.kt
> +    selectedTheaters: MutableState<Set<String>>,
여기도요!

2024-11-25 15:43 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/component/SelectableTheatersInModal.kt
> +    var isSelected by remember { mutableStateOf(false) }
여기도요!

2024-11-25 15:43 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/component/TheaterClassificationTabInModal.kt
> +    selectedTabInModalIndex: MutableState<Int>,
이 부분도 상태 관리 부분 같은데, 뷰모델로 가야할 거 같아요!

2024-11-25 15:43 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/component/TheaterClassificationTabInModal.kt
> +                    selected = selectedTabInModalIndex.value == index,
헉 요거 Tab이 Material Design의 내장 컴포넌트라서 그런 거 같은데 맞나요?
그렇다면 커스텀 탭을 만들어야 할 거 같아요!

2024-11-25 15:43 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/component/TheaterSelectionModalBottomSheet.kt
> +    if (isSheetOpen.value) {
여기에서도 모든 상태관리는 뷰모델에서 이루어지면 더 좋을 거 같아요!

2024-11-25 15:43 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/component/TheaterSelectionModalFooter.kt
> +    val coroutineScope = rememberCoroutineScope()
여기도 상태관리는 뷰모델로 가는 편이 더 좋을 거 같아요!

2024-11-25 15:43 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/component/TimeScreen.kt
> +    val selectedTheaters = remember { mutableStateOf(setOf<String>()) }
여기도 뷰모델로 이동하면 좋을 거 같습니다!

2024-11-26 06:23 UTC, 0se0 reviewed
예시를 달아 코드리뷰 다시 남겨드립니다~!

2024-11-26 06:23 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/component/ClickableVerticalRegionListInModal.kt
> +    selectedRegionInModal: MutableState<String>,
```suggestion
     selectedRegion: String,
    onRegionSelected: (String) -> Unit,
```
State Hoisting을 진행해주신 점 좋습니다!! 다만, 
컴포넌트는 상태 관리가 아닌 UI 표시에만 집중하여 구현해주신다고 보면 될 거 같아요!

2024-11-26 06:23 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/component/ClickableVerticalRegionListInModal.kt
> +        }
위 부분 처럼 호이스팅을 해주시면 이벤트 핸들링 부분에서도 상태 변경 로직이 콜백을 통해 외부로 이동할 수 있을 거 같습니다!

2024-11-26 06:23 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/component/SelectableTheatersInModal.kt
> +    selectedTheaters: MutableState<Set<String>>,
```suggestion
    selectedTheaters: Set<String>,
    onTheaterSelected: (String) -> Unit
```

여기 부분도 이렇게 수정해주시면 상태 관리 책임이 컴포넌트 외부로 이동할 수 있을 거 같아요. 지금 대부분의 코드에서 MutableState를 직접 전달하는 대신 불변 데이터와 콜백 함수를 전달한다고 보시면 쉬울 거 같습니다!

2024-11-26 06:23 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/component/SelectableTheatersInModal.kt
> +    selectedTheaters: MutableState<Set<String>>,
```suggestion
     isSelected: Boolean,
    onTheaterClick: () -> Unit
```
여기서도 이렇게 바꿔주시면

상태 관리와 이벤트 처리가 개선될 수 있을 거 같아요!

1. 상태 관리
기존에` var isSelected by remember { mutableStateOf(false) }`로 컴포넌트 내부에서 상태를 직접 관리하던 것을
`isSelected: Boolean` 파라미터로 상태를 외부에서 전달받아 단방향 데이터 흐름 구현할 수 있습니다!


2. 이벤트 처리
기존에 컴포넌트 내부에서 상태 변경 로직을 직접 처리하신 거 같은데, `onTheaterClick: () -> Unit` 콜백을 통해 클릭 이벤트만 전달하고 실제 처리는 외부로 위임이 가능합니다.

이렇게 하면 컴포넌트는 데이터를 표시하고 이벤트를 전달하는 순수한 UI 표현에 집중할 수 있을 거 같아요!

2024-11-26 06:23 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/component/SelectableTheatersInModal.kt
> +            }
위에처럼 바꾸게 된다면
여기 선택 로직에서도 훨씬 간소화 될 수 있을 것 같습니다~

2024-11-26 06:23 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/component/TheaterClassificationTabInModal.kt
> +    selectedTabInModalIndex: MutableState<Int>,
```suggestion
    selectedTabIndex: Int,
    onTabSelected: (Int) -> Unit
```
여기서도 MutableState를 직접 전달하는 대신 불변 값(Int)과 이벤트 콜백을 전달하면
상태 변경 로직이 컴포넌트 외부로 이동하여 **컴포넌트는 상태 표시와 이벤트 전달만 담당**할 수 있을 거 같아요!

2024-11-26 06:23 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/component/TheaterClassificationTabInModal.kt
> +                    onClick = { selectedTabInModalIndex.value = index },
그렇게 되면 여기 onClick에서도 상태 변경 로직을 콜백으로 위임했기에 컴포넌트는 클릭 이벤트만 전달하는 순수한 UI 역할을 하는 코드를 구현해볼 수 있을 거 같습니다!

2024-11-26 06:23 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/component/TheaterSelectionModalBottomSheet.kt
> +    modifier: Modifier = Modifier
```suggestion
   isSheetOpen: Boolean,
   selectedTabIndex: Int,
   selectedRegion: String,
   selectedTheaters: Set<String>
   
   onTabSelected: (Int) -> Unit,
   onRegionSelected: (String) -> Unit,
   onTheaterSelected: (String) -> Unit,
   onTheaterDeselected: (String) -> Unit
```
(MutableState만 수정)(이벤트 핸들링 추가)

이렇게 구현하면 MutableState를 직접 전달하는 대신 불변 값을 전달하고 상태 관리 책임을 컴포넌트 외부로 이동시킬 수 있습니다!
그리고 각각의 이벤트에 대한 콜백 함수 추가 상태 변경 로직을 외부로 위임하여
컴포넌트를 UI 표시와 이벤트 전달만 담당할 수 있도록 구현 가능할 거 같아요.

2024-11-26 06:23 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/component/TheaterSelectionModalBottomSheet.kt
> +    if (isSheetOpen.value) {
그리고 이거는 그냥 이야기 하는 건데
sheetstate을 타고 들어가보니까 deprecated 되었다고 뜨더라구요..? 그래서
 if 문 안에서   ` val sheetState = rememberModalBottomSheetState(skipPartiallyExpanded = true)`
을 구현하여 BottomSheet의 상태 관리를 컴포넌트 내부로 이동 하는 것은 어떠실지요!

2024-11-26 06:23 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/component/TheaterSelectionModalFooter.kt
> +    selectedTheaters: MutableState<Set<String>>,
여기서도
```suggestion
    selectedTheaters: Set<String>,
    onTheaterDeselected: (String) -> Unit
```
MutableState를 직접 전달하는 대신 불변 값과 이벤트 콜백을 전달하여
상태 변경 로직을 컴포넌트 외부로 이동시키고 칩 삭제 로직을 콜백 함수로 분리시키면 좋을 거 같아요! 이유는 같습니다!

2024-11-26 06:23 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/component/TimeScreen.kt
> +    )
코드리뷰를 모두 반영한 코드가 된다면 여기 부분도 바뀔 거 같네욥!

2024-11-26 08:29 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/time/component/ClickableVerticalRegionListInModal.kt
> +    selectedRegionInModal: MutableState<String>,
진짜 이말듣고 이해되었습니다.. 왜 그렇게 해야하는지도 공부했습니다!

2024-11-26 08:55 UTC, kamja0510 commented on app/src/main/java/org/sopt/cgv/feature/time/component/TheaterSelectionModalBottomSheet.kt
> +    if (isSheetOpen.value) {
density가 없는 생성자가 deprecated인데 remeberModalBottomSheetState()로 생성되는 SheetState는 density가 전달된 SheetState라 괜찮지 않을까요?
제가 내부코드를 잘못 해석했다면 죄송합니다 ㅠ

2024-11-26 09:09 UTC, 0se0 commented on app/src/main/java/org/sopt/cgv/feature/time/component/TheaterSelectionModalBottomSheet.kt
> +    if (isSheetOpen.value) {
헉 그렇네요!!👍👍

2024-11-26 09:10 UTC, 0se0 approved these changes
수고 많으셨습니다!!!👏👍첵오

2024-11-26 15:46 UTC, tunaunnie approved these changes

2024-11-26 16:02 UTC, merged